# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hfl.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('button_text', models.CharField(max_length=50)),
                ('description1', models.TextField(help_text=b'For the front of the display card')),
                ('description2', models.TextField(help_text=b'For the back of the display card')),
                ('image', models.ImageField(upload_to=b'static/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to=b'static/images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('office_phone_number', models.CharField(blank=True, max_length=30)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=30)),
                ('url_path', models.CharField(help_text=b'The path to be displayed for that agent e.g (/agents/charles-g-lane)', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to=b'static/images/%Y/%m/%d')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_one', models.CharField(max_length=100)),
                ('heading_two', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_listing', models.NullBooleanField(default=False, help_text=b'Determine which listing to profile ')),
                ('property_name', models.CharField(blank=True, help_text=b'Property will either be referred by their street address or this field if set', max_length=50)),
                ('listing_features', models.TextField(help_text=b'Input the features in as a comma delimted list', max_length=900)),
                ('street_address', models.CharField(max_length=80)),
                ('county', models.CharField(max_length=60)),
                ('zip', models.CharField(max_length=30)),
                ('zoning', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(choices=[(b'Land', b'Land'), (b'Commercial', b'Commercial'), (b'Residential', b'Residential')], default=b'LAND', max_length=20)),
                ('status', models.CharField(blank=True, choices=[(b'Available', b'Available'), (b'Under Contract', b'Under Contract'), (b'Sold', b'Sold')], default=b'Available', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('property_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField()),
                ('year_built', models.CharField(blank=True, max_length=40)),
                ('tax_map', models.CharField(blank=True, max_length=30)),
                ('directions', models.TextField(blank=True)),
                ('baths_total', models.CharField(blank=True, max_length=100)),
                ('baths_full', models.CharField(blank=True, max_length=100)),
                ('baths_half', models.CharField(blank=True, max_length=100)),
                ('acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('amenities', models.TextField(blank=True)),
                ('heating', models.CharField(blank=True, max_length=100)),
                ('cooling', models.CharField(blank=True, max_length=100)),
                ('utilities', models.CharField(blank=True, max_length=100)),
                ('stories', models.CharField(blank=True, max_length=50)),
                ('rent_potential', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('hoa', models.NullBooleanField()),
                ('hoa_dues', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('extras', models.TextField(blank=True)),
                ('garage', models.NullBooleanField()),
                ('bedrooms', models.CharField(blank=True, max_length=50)),
                ('square_feet', models.CharField(blank=True, max_length=50, null=True)),
                ('appliances', models.CharField(blank=True, max_length=100)),
                ('truck_bays', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('slab_depth', models.CharField(blank=True, max_length=20, null=True)),
                ('ceiling_height', models.CharField(blank=True, max_length=20, null=True)),
                ('closing_date', models.DateField(blank=True)),
                ('air_conditioned_space', models.CharField(blank=True, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True)),
                ('lng', models.FloatField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfl.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=b'static/images/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('main_image', models.NullBooleanField(help_text=b'For the image that will display wide across the page')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hfl.Listing')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='ListingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to=b'static/videos/%Y/%m/%d', validators=[hfl.validators.validate_video_extension])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfl.Listing')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='listing',
            field=models.ForeignKey(help_text=b'Need to chose listing for routing purposes', on_delete=django.db.models.deletion.CASCADE, to='hfl.Listing'),
        ),
        migrations.AddField(
            model_name='landingcontent',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hfl.ListingVideo'),
        ),
        migrations.AddField(
            model_name='aboutoption',
            name='about_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='hfl.AboutPage'),
        ),
    ]
