# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[(b'Land', b'Land'), (b'Commercial', b'Commercial'), (b'Residential', b'Residential')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type_choices',
            field=models.ManyToManyField(to='hfl.PropertyType'),
        ),
    ]
