# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0002_auto_20180314_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingcontent',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hfl.ListingVideo'),
        ),
    ]
