# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0003_auto_20180314_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
