# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0005_auto_20180314_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingcontent',
            name='sort_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
