# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0006_auto_20180314_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='url_path',
            field=models.CharField(help_text=b'The path to be displayed for that agent e.g (charles-g-lane)', max_length=50),
        ),
    ]
