# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0008_auto_20180321_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='terrastride_iframe',
            field=models.TextField(blank=True, help_text=b"Paste terrastride linke directly into input. E.G  'https://app.terrastridepro.com/property/34975/map?referer=iframe'", null=True),
        ),
    ]
