# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0011_auto_20180325_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
