# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0012_auto_20180419_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
