# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 20:00
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Listing = apps.get_model("hfl", "Listing")
    for listing in Listing.objects.all():
        listing.agents.add(listing.agent)

class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0014_listing_agents'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
