# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0017_auto_20190321_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['weight'], 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AddField(
            model_name='listingimage',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text=b'The response will be ordered from highest to lowest'),
        ),
    ]
