# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0018_auto_20190423_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['-weight'], 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AddField(
            model_name='listing',
            name='youtube_link',
            field=models.TextField(blank=True, help_text=b'Paste youtube link here that you want shown on listing video.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listingvideo',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='hfl.Listing'),
        ),
    ]
