# Generated by Django 2.2.7 on 2020-05-11 23:30

from django.db import migrations, models
import django.db.models.deletion
import hfl.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hfl', '0019_auto_20191029_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='three_d_tour_src',
            field=models.CharField(blank=True, help_text='3D Viewer such as: https://app.immoviewer.com/portal/tour/1777989?accessKey=5ebb', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='aboutoption',
            name='description1',
            field=models.TextField(help_text='For the front of the display card'),
        ),
        migrations.AlterField(
            model_name='aboutoption',
            name='description2',
            field=models.TextField(help_text='For the back of the display card'),
        ),
        migrations.AlterField(
            model_name='aboutoption',
            name='image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='background_image',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='avatar',
            field=models.ImageField(upload_to='static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='url_path',
            field=models.CharField(help_text='The path to be displayed for that agent e.g (charles-g-lane)', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='listing',
            field=models.ForeignKey(help_text='Need to chose listing for routing purposes', on_delete=django.db.models.deletion.CASCADE, to='hfl.Listing'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='hfl.ListingVideo'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='display_listing',
            field=models.NullBooleanField(default=False, help_text='Determine which listing to profile '),
        ),
        migrations.AlterField(
            model_name='listing',
            name='html_description',
            field=models.TextField(blank=True, help_text='To manually edit the meta description field for a listing.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='html_title',
            field=models.TextField(blank=True, help_text='To manually edit the meta title field for a listing.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_features',
            field=models.TextField(help_text='Input the features in as a comma delimted list', max_length=900),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_name',
            field=models.CharField(blank=True, help_text='Property will either be referred by their street address or this field if set', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('Land', 'Land'), ('Commercial', 'Commercial'), ('Residential', 'Residential')], default='LAND', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Under Contract', 'Under Contract'), ('Sold', 'Sold'), ('Leased', 'Leased'), ('Draft', 'Draft')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='terrastride_src',
            field=models.CharField(blank=True, help_text="Paste terrastride linke directly into input. E.G  'https://app.terrastridepro.com/property/34975/map?referer=iframe'", max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='youtube_link',
            field=models.TextField(blank=True, help_text='Paste youtube link here that you want shown on listing video.', max_length=200),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='main_image',
            field=models.NullBooleanField(help_text='For the image that will display wide across the page'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='The response will be ordered from highest to lowest'),
        ),
        migrations.AlterField(
            model_name='listingvideo',
            name='file',
            field=models.FileField(upload_to='static/videos/%Y/%m/%d', validators=[hfl.validators.validate_video_extension]),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='property_type',
            field=models.CharField(choices=[('Land', 'Land'), ('Commercial', 'Commercial'), ('Residential', 'Residential')], max_length=20),
        ),
    ]
