runtime: python
env: flex
service: backend-app
entrypoint: gunicorn -b :$PORT hfl.wsgi
manual_scaling:
  instances: 1
resources:
 cpu: .5
 memory_gb: 2
 disk_size_gb: 10
runtime_config:
  python_version: 3