branch-defaults:
  default:
    environment: staging
  master:
    environment: production
    group_suffix: null
global:
  application_name: hfl-site-python3
  branch: null
  default_ec2_keyname: hfl
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: hfl
  repository: null
  sc: null
  workspace_type: Application
